# Generated by Django 5.2 on 2025-04-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
        migrations.AlterField(
            model_name='order',
            name='summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.ManyToManyField(to='products.card'),
        ),
    ]
